name: Sync Past Leetcode Solutions

on:
  workflow_dispatch: # Allows you to trigger this manually with a single button click

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Solutions
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions # Subfolder where your codes will sit
          verbose: true
